/**
 * Alpha Centauri Protocol - Centralized UI Strings & Institutional Copy Dictionary
 * 
 * All UI labels, headers, descriptions, disclaimers, modal texts, action summaries,
 * and toast notification messages are centralized here for strict maintainability,
 * terminology consistency, and internationalization (i18n) readiness.
 */

export const UI_STRINGS = {
  COMMON: {
    APP_NAME: 'Alpha Centauri Protocol',
    SYMBOL_ALPHA: 'ALPHA',
    SYMBOL_USDC: 'USDC',
    SYMBOL_STALPHA: 'stALPHA',
    SYMBOL_WBTC: 'WBTC',
    SYMBOL_WETH: 'WETH',
    SYMBOL_USDT: 'USDT',
    BTN_CONFIRM: 'Confirmar',
    BTN_CANCEL: 'Cancelar',
    BTN_CLOSE: 'Cerrar',
    BTN_CLAIM: 'Cobrar',
    BTN_PROCESSING: 'Procesando...',
    BTN_SIGNING: '⏳ Firmando...',
    BTN_SIGN_AND_CONFIRM: '✍️ Confirmar y Firmar',
    STATUS_ACTIVE: 'Activo',
    STATUS_INACTIVE: 'Inactivo',
    STATUS_MATURED: 'Vencido',
    STATUS_LOCKED: 'Bloqueado',
    STATUS_DISCONNECTED: 'Desconectado',
    STATUS_ON_CHAIN: 'On-Chain',
    STATUS_FROZEN: 'Congelado',
    STATUS_NORMAL: 'NORMAL',
    STATUS_FROZEN_FULL: 'FROZEN (Congelado)',
    STATUS_AVAILABLE: 'Disponible',
    STATUS_FUNDED: 'Financiado',
    STATUS_REPAID: 'Reembolsado',
    STATUS_LIQUIDATED: 'Liquidado',
    STATUS_CANCELLED: 'Cancelado',
    STATUS_COMPLETED: 'Completado',
    STATUS_SECURE_RATIO: '140% (Seguro)',
    NOT_AVAILABLE: 'N/A',
    ESTIMATED_TIME: 'Tiempo Estimado',
    GAS_FEE: 'Comisión de Red',
    SELECT_OPTION_DEFAULT: '-- Selecciona una opción --',
    NO_POSITIONS_AVAILABLE: '-- No tienes NFTs de posición disponibles --',
    CONTRACT_TARGET_LABEL: 'Contrato Objetivo:',
    OPERATIONAL_SUMMARY_TITLE: 'Resumen Operativo & Parámetros',
    TAB_PORTAL_CLIENT: '💎 Portal Cliente & Bonos',
    TAB_METRICS_ANALYTICS: '📊 Métricas & Analítica',
    TAB_GOVERNANCE_OPERATIONS: '🏛️ Operaciones Protocolo & Gobernanza DAO',
    BTN_INVITE_FRIENDS: '🎁 Invitar Amigos',
    EVM_BLOCK_LABEL: '🕒 Bloque EVM:'
  },

  NAV_TABS: {
    PORTAL: '🏛️ Tesorería & Rendimiento',
    STAKING: '🔒 Staking & Real Yield',
    BONDS: '📜 Bonos con Descuento',
    P2P: '🤝 Préstamos P2P & Tesorería',
    METRICS: '📊 Métricas & Proof of Reserves',
    GOVERNANCE: '⚖️ Gobernanza DAO',
    ADMIN: '🛡️ Control Panel & Admin'
  },

  HEADER: {
    TITLE: 'ALPHA CENTAURI PROTOCOL',
    BADGE_ENV_PROD: 'PURE DEFI v2.4 (MAINNET)',
    BADGE_ENV_SANDBOX: 'SANDBOX (DEVNET)',
    LABEL_TVL: 'TVL RESERVAS:',
    LABEL_NAV: 'VALOR NAV / SHARE:',
    LABEL_WALLET_STATUS: 'ESTADO WALLET',
    LABEL_WEB3_CONNECTION: 'CONEXIÓN WEB3:',
    LABEL_POR_RATIO: 'RATIO COLATERAL PoR',
    LABEL_APY_BREAKDOWN_TOOLTIP: '⚡ APY ALPHA (DESGLOSE 🔍)',
    BTN_CONNECT: 'Conectar Wallet',
    BTN_DISCONNECT: 'Desconectar'
  },

  TREASURY: {
    TITLE: '🏛️ Tesorería del Protocolo & Bóvedas de Rendimiento',
    SUBTITLE: 'Respaldo 100% On-Chain en Bóvedas Institucionales con Generación Automática de Real Yield.',
    BADGE_ACTIVE: 'Reserva Activa 100%',
    MORPHO_TITLE: 'MORPHO VAULT YIELD ADAPTER',
    MORPHO_DESC: 'El 80% de las reservas líquidas en USDC se colocan automáticamente en Morpho Blue para generar rendimientos de bajo riesgo.',
    CARD_DEPOSIT_TITLE: '💵 Depósito en Tesorería (Acuñar ALPHA Shares)',
    CARD_DEPOSIT_DESC: 'Deposita USDC para acuñar nuevas participaciones ALPHA a valor NAV actual con slippage dinámico adaptativo.',
    INPUT_DEPOSIT_LABEL: 'Monto USDC a Depositar:',
    INPUT_DEPOSIT_PLACEHOLDER: 'ej. 1000',
    DYNAMIC_FEE_LABEL: 'Comisión Dinámica Adaptativa:',
    DYNAMIC_FEE_SUBTEXT: '50% inyectado a Reservas Tesorería / 50% distribuido como Liquid Real Yield a stakers.',
    ESTIMATED_SHARES_LABEL: 'ALPHA Shares Estimadas a Recibir:',
    BTN_DEPOSIT: '💵 Confirmar Depósito en Tesorería',
    CARD_REDEEM_TITLE: '🏛️ Rescate de Shares ALPHA (Canje por USDC)',
    CARD_REDEEM_DESC: 'Quema tus participaciones ALPHA para canjearlas inmediatamente por USDC respaldado en reservas a valor NAV.',
    INPUT_REDEEM_LABEL: 'Monto de ALPHA Shares a Rescatar:',
    INPUT_REDEEM_PLACEHOLDER: 'ej. 500',
    REDEEM_FEE_LABEL: 'Comisión de Rescate (1.00% Fija):',
    REDEEM_FEE_SUBTEXT: '0.50% acrece el NAV del protocolo / 0.50% distribuido a la bóveda de Real Yield.',
    ESTIMATED_USDC_LABEL: 'USDC Netos Estimados a Recibir:',
    BTN_REDEEM: '🏛️ Confirmar Rescate de Shares',
    CARD_FAUCET_TITLE: '🚰 Faucet de USDC de Prueba',
    CARD_FAUCET_DESC: 'Obtén 10,000 USDC mock para probar todas las operaciones del protocolo en el entorno de desarrollo local.',
    BTN_FAUCET: '🚰 Solicitar 10,000 USDC Mock',
    CARD_POR_TITLE: '🔍 Auditoría de Proof of Reserves (PoR)',
    CARD_POR_DESC: 'Verifica la solvencia en tiempo real consultando la valuación de todos los activos auditados por oráculos Chainlink.',
    BTN_AUDIT_POR: '🔍 Ejecutar Auditoría PoR On-Chain',
    LABEL_MY_USDC_BALANCE: 'MI BALANCE DISPONIBLE',
    LABEL_MY_ALPHA_SHARES: 'MIS ALPHA SHARES',
    BTN_HARVEST_MORPHO: '🌾 Cosechar Rendimiento Diario (Morpho Harvest)',
    STRAT_STABLES_TITLE: '💵 Stablecoins (USDC / USDT)',
    STRAT_STABLES_BADGE: 'Real Yield Active',
    STRAT_STABLES_P2P: '• Créditos Directos / P2P:',
    STRAT_STABLES_MORPHO: '• Bóvedas Morpho Blue:',
    STRAT_BTC_TITLE: '₿ Bitcoin (WBTC / cbBTC)',
    STRAT_BTC_BADGE: 'Babylon & Morpho',
    STRAT_BTC_RESERVE: '• Reserva On-Chain Auditada:',
    STRAT_ETH_TITLE: 'Ξ Ethereum (WETH / stETH)',
    STRAT_ETH_BADGE: 'Staking & Vaults',
    STRAT_ETH_RESERVE: '• Reserva On-Chain Auditada:'
  },

  STAKING: {
    TITLE: '🔒 Staking de Gobernanza & Flywheel Real Yield',
    SUBTITLE: 'Bloquea ALPHA para obtener stALPHA, participar en votaciones DAO y acumular dividendos de Real Yield.',
    METRIC_TOTAL_STAKED: 'Total ALPHA en Staking',
    METRIC_CIRCULATING: 'Suministro Circulante',
    METRIC_STAKING_RATIO: 'Ratio de Staking Global',
    METRIC_TOTAL_BURNED: 'Tokens ALPHA Quemados',
    CARD_STAKE_TITLE: '📥 Bloquear Tokens ALPHA en Staking',
    CARD_STAKE_DESC: 'Aplica una comisión del 1.00% al ingresar: 50% se quema permanentemente (deflación) y 50% va a CommunityYieldVault.',
    INPUT_STAKE_LABEL: 'Monto ALPHA a Bloquear:',
    INPUT_STAKE_PLACEHOLDER: 'ej. 1000',
    BTN_STAKE: '🔒 Bloquear ALPHA en Staking',
    CARD_UNSTAKE_TITLE: '📤 Retirar (Unstake) ALPHA Tokens',
    CARD_UNSTAKE_DESC: 'Libera tus tokens ALPHA bloqueados de vuelta a tu billetera sin comisiones ni penalizaciones.',
    INPUT_UNSTAKE_LABEL: 'Monto stALPHA a Liberar:',
    INPUT_UNSTAKE_PLACEHOLDER: 'ej. 500',
    BTN_UNSTAKE: '🔓 Confirmar Retiro (Unstake)',
    CARD_YIELD_TITLE: '🎁 Dividendos de Real Yield Devengados',
    CARD_YIELD_DESC: 'Reclama tus dividendos acumulados provenientes de comisiones de tesorería, préstamos P2P y rendimientos de bóvedas.',
    LABEL_ACCUMULATED_YIELD: 'Rendimiento Acumulado Disponible:',
    LABEL_MY_STAKED: 'TU STAKING (stALPHA)',
    LABEL_REAL_YIELD_ACCUM: 'REAL YIELD ACUMULADO',
    PREF_TITLE: '🔀 Real Yield Router & Preferencia Payout',
    PREF_OPTION_A: 'Opción A: USDC Directo (100% Líquido)',
    PREF_OPTION_B: 'Opción B: Activos de Reserva (WBTC & WETH Pro-Rata)',
    BTN_CLAIM_YIELD: '🎁 Reclamar Dividendos Real Yield',
    BTN_GASLESS_CLAIM: '⚡ Reclamar vía Gasless (YieldStreamingVault)',
    BENEFIT_NOTE: 'Los titulares de stALPHA obtienen automáticamente hasta un +5.00% extra de descuento en Bonos Vestados.',
    BADGE_DEFLATIONARY: '🔥 Deflacionario'
  },

  VESTED_VAULTS: {
    TITLE: '📜 Bonos con Descuento (Vested Discount Vaults)',
    SUBTITLE: 'Adquiere tokens ALPHA con hasta 25% de descuento sobre el valor NAV a cambio de un periodo de bloqueo vesting.',
    CARD_BUY_TITLE: '🎯 Adquirir Bono con Descuento',
    CARD_BUY_DESC: 'Selecciona el plazo de bloqueo deseado. A mayor plazo, mayor es el descuento aplicado sobre el precio NAV.',
    LABEL_PRINCIPAL: 'Monto Principal a Invertir (USDC):',
    LABEL_LOCK_YEARS: 'Plazo de Bloqueo:',
    YEAR_1: '1 Año — 5.0% Descuento Base',
    YEAR_2: '2 Años — 10.0% Descuento Base',
    YEAR_3: '3 Años — 15.0% Descuento Base',
    YEAR_4: '4 Años — 20.0% Descuento Base',
    YEAR_5: '5 Años — 25.0% Descuento Base',
    LABEL_REFERRER: 'Dirección del Referidor (Opcional):',
    REFERRER_PLACEHOLDER: '0x...',
    BTN_MY_REFERRAL_LINK: '🎁 Mi Enlace de Referido',
    DISCOUNT_SUMMARY_TITLE: 'Resumen de Compra:',
    LABEL_PRICE_TO_PAY: 'Precio con Descuento a Pagar:',
    LABEL_ESTIMATED_SAVINGS: 'Ahorro Obtenido:',
    BTN_BUY_BOND: '📜 Adquirir Bono Vestado (Acuñar NFT Posición)',
    TABLE_TITLE: '📋 Tus Posiciones de Bonos Vestados (NFTs de Posición)',
    TABLE_EMPTY: 'No tienes bonos vestados activos en tu billetera.',
    TH_TOKEN_ID: 'ID NFT',
    TH_PRINCIPAL: 'Principal (USDC)',
    TH_LOCK_PERIOD: 'Bloqueo',
    TH_MATURITY_DATE: 'Fecha de Vencimiento',
    TH_STATUS: 'Estado',
    TH_ACTIONS: 'Acciones',
    BTN_CLAIM_MATURED: '🏆 Reclamar (100%)',
    BTN_RAGEQUIT: '⚠️ Ragequit (-15%)',
    RAGEQUIT_WARNING: 'Ragequit aplica una penalización irreversible del 15% (7.5% a Reservas / 7.5% a Stakers).',
    BADGE_RAGEQUITTED: 'Ragequitted',
    BADGE_CLAIMED: 'Reclamado'
  },

  P2P_MARKETPLACE: {
    TITLE: '🤝 Marketplace de Préstamos P2P & Línea de Crédito Institucional',
    SUBTITLE: 'Usa tus NFTs de posición de bonos vestados o colaterales ERC20 para solicitar créditos en USDC.',
    TAB_ALL_OFFERS: 'Todas las Ofertas',
    TAB_AVAILABLE: 'Disponibles',
    TAB_FUNDED: 'Financiados',
    TAB_MY_LOANS: 'Mis Préstamos',
    TAB_BORROW_TREASURY: '🏛️ Crédito Tesorería (Inmediato)',
    TAB_CREATE_OFFER: '🤝 Publicar Oferta P2P',
    CARD_TREASURY_TITLE: '🏛️ Línea de Crédito Directa de la Tesorería (8.00% APR)',
    CARD_TREASURY_DESC: 'La Tesorería del protocolo financia préstamos instantáneos en USDC respaldados por tus garantías en custodia.',
    LABEL_COL_TYPE: 'Tipo de Colateral a Utilizar:',
    COL_NFT: 'NFT de Posición de Bono (70% Max LTV)',
    COL_ALPHA: 'ALPHA Token (50% Max LTV)',
    COL_WBTC: 'Wrapped Bitcoin - WBTC (70% Max LTV)',
    COL_WETH: 'Wrapped Ethereum - WETH (75% Max LTV)',
    LABEL_NFT_SELECT: 'Selecciona el NFT de tu Billetera:',
    LABEL_REQ_COL_AMOUNT: 'Garantía Requerida Calculada:',
    LABEL_BORROW_AMOUNT: 'Monto USDC a Solicitar:',
    LABEL_DURATION_DAYS: 'Duración del Préstamo (Días):',
    BTN_BORROW_TREASURY: '🏛️ Solicitar Crédito a la Tesorería',
    CARD_OFFER_TITLE: '🤝 Publicar Oferta de Préstamo P2P',
    CARD_OFFER_DESC: 'Deposita tu NFT de Posición como garantía en el contrato de escrow y define tu tasa de interés deseada.',
    LABEL_OFFER_NFT: 'NFT Token ID a Colateralizar:',
    LABEL_OFFER_AMOUNT: 'Monto a Solicitar (USDC):',
    LABEL_OFFER_INTEREST: 'Tasa de Interés Propuesta (BPS / APR):',
    LABEL_OFFER_DURATION: 'Plazo del Préstamo (Días):',
    BTN_CREATE_OFFER: '🤝 Publicar Oferta en el Marketplace',
    TABLE_MARKET_TITLE: '📈 Ofertas de Préstamo Disponibles en el Mercado',
    TABLE_MARKET_EMPTY: 'No hay ofertas de préstamo abiertas actualmente en el mercado.',
    TH_LOAN_ID: 'ID',
    TH_BORROWER: 'Prestatario',
    TH_COLLATERAL: 'Colateral',
    TH_AMOUNT: 'Monto (USDC)',
    TH_APR: 'Tasa APR',
    TH_DURATION: 'Plazo',
    TH_HEALTH: 'Health Factor',
    TH_ACTIONS: 'Acción',
    BTN_FUND_LOAN: '✅ Financiar',
    BTN_CANCEL_OFFER: '❌ Cancelar',
    BTN_REPAY_LOAN: '💰 Reembolsar',
    BTN_LIQUIDATE_LOAN: '⚡ Liquidar',
    TAG_RESERVE_ACTIVE: '🛡️ Fondo de Reserva Activo',
    TAG_FIXED_RATE: '⚡ Tasa Fija Tesorería On-Chain',
    CARD_ACTIVE_LOANS_TITLE: '💳 Mis Préstamos Solicitados & Activos',
    CARD_ACTIVE_LOANS_DESC: 'Aquí puedes ver claramente todos los préstamos solicitados u ofertas activas y reembolsarlos o cancelarlos en 1-clic para gestionar tu custodia.',
    LABEL_MANUAL_MANAGER: '⚖️ Gestor Manual por ID',
    DESC_MANUAL_MANAGER: 'Financia, reembolsa o liquida préstamos ingresando directamente el ID correspondiente.',
    LABEL_TARGET_LOAN_ID: 'ID Préstamo Objetivo:',
    LABEL_REQ_COL_PERCENT: 'Colateral USDC Requerido (130%-150%):'
  },

  METRICS: {
    TITLE: '📊 Métricas Institucionales & Proof of Reserves en Tiempo Real',
    SUBTITLE: 'Auditoría matemática de solvencia, liquidez en bóvedas y respaldo financiero del protocolo.',
    SOLVENCY_CARD_TITLE: 'Ratio de Solvencia Global (PoR)',
    TOTAL_ASSETS_LABEL: 'Total Activos en Reservas (USD):',
    TOTAL_LIABILITIES_LABEL: 'Total Pasivos Emitidos (USD):',
    BACKING_STATUS_HEALTHY: '100% Respaldado & Solvente',
    BACKING_STATUS_WARNING: 'Atención: Ratio Cercano al Umbral',
    TABLE_ASSETS_TITLE: 'Desglose de Reservas & Bóvedas Exógenas',
    TH_ASSET: 'Activo',
    TH_ALLOCATION: 'Asignación Actual',
    TH_TARGET_WEIGHT: 'Peso Objetivo Target',
    TH_ORACLE_PRICE: 'Precio Oráculo Chainlink',
    TH_TOTAL_VALUE_USD: 'Valoración en USD',
    TH_YIELD_SOURCE: 'Fuente de Rendimiento',
    MORPHO_USDC_SOURCE: 'Morpho Blue Lending Vault',
    LOMBARD_LBTC_SOURCE: 'Lombard LBTC Liquid Staking',
    LIDO_WSTETH_SOURCE: 'Lido wstETH Liquid Staking',
    P2P_SPREAD_SOURCE: 'Préstamos P2P & Margin Spreads',
    BTN_APY_MATH_MODAL: '⚡ Desglose Matemático APY',
    LABEL_SOLVENCY_FORMULA: 'Ratio Solvencia = Total Activos / Pasivos',
    LABEL_NAV_BACKING: '💎 Respaldo (NAV / ALPHA)',
    LABEL_NAV_NET_WORTH: 'Valor Patrimonial Neto On-Chain',
    LABEL_RESERVES_COMPOSITION: 'USDC + WBTC + WETH en Reservas',
    LABEL_OBLIGATIONS: 'Obligaciones con Tenedores de ALPHA',
    TOKENOMICS_TITLE: '🥩 Tokenomics & Estado de Oferta Deflacionaria',
    LABEL_FREE_FLOAT: 'Suministro Libre Flotante',
    LABEL_COMMUNITY_STAKE: '👤 Stake Comunidad',
    LABEL_COMMUNITY_LOCKED: 'Bloqueado por Inversores',
    LABEL_VAULT_STAKE: '💎 Stake Bóveda Comunitaria',
    LABEL_RESERVES_STAKE: '🏛️ Stake Reservas',
    LABEL_SUBRESERVE_TREASURY: 'Sub-Reserva Tesorería',
    LABEL_TOTAL_STALPHA: 'Total stALPHA en Gobernanza',
    LABEL_IRREVERSIBLE_BURN: 'Quema Definitiva Irreversible',
    LABEL_DESTROYED_SUFFIX: 'Destruidos'
  },

  GOVERNANCE: {
    TITLE: '⚖️ Centro de Comando de Gobernanza DAO',
    SUBTITLE: 'Propuestas de gobernanza on-chain, control descentralizado y Timelock de 72 horas.',
    CARD_PROPOSE_TITLE: '🏛️ Crear Nueva Propuesta de Gobernanza',
    LABEL_TARGET_CONTRACT: 'Contrato Objetivo (Target Address):',
    LABEL_CALLDATA: 'Datos Calldata Codificados (Bytes):',
    LABEL_DESCRIPTION: 'Descripción de la Propuesta:',
    BTN_SUBMIT_PROPOSAL: '🏛️ Enviar Propuesta a GovernorAlphaCentauri',
    PROPOSALS_TABLE_TITLE: '📜 Historial y Estado de Propuestas DAO',
    TH_PROP_ID: 'ID Propuesta',
    TH_DESCRIPTION: 'Descripción',
    TH_VOTES_FOR: 'Votos A Favor',
    TH_VOTES_AGAINST: 'Votos En Contra',
    TH_STATUS: 'Estado Timelock',
    TH_VOTE_ACTION: 'Votar',
    BTN_VOTE_FOR: '👍 A Favor',
    BTN_VOTE_AGAINST: '👎 En Contra',
    BTN_EXECUTE_TIMELOCK: '⚡ Ejecutar Timelock',
    BANNER_EVM_CHAIN: 'EVM CHAIN DETECTADO',
    BANNER_POR_RATIO: 'RATIO SOLVENCIA PoR',
    BANNER_NAV_TOKEN: 'NAV / TOKEN',
    TAB_AUDIT_METRICS: '📊 Auditoría & Métricas',
    TAB_PARAM_CONTROL: '⚙️ Control Parámetros',
    TAB_PROTOCOL_VAULTS: '💼 Bóvedas del Protocolo',
    TAB_PROMOTIONS: '🎁 Eventos & Promociones',
    TAB_SECURITY: '🛡️ Consola Seguridad',
    COVERAGE_VERIFIED: 'Cobertura On-Chain 100% Verificada',
    BURNED_BY_FEES: 'Tokens Destruidos por Fees Staking',
    INCOME_MODEL_TITLE: 'MODELO DE INGRESOS LIQUIDUS (50/50)',
    INCOME_MODEL_DESC: '🏛️ 50% Res. Tesorería | 🏦 50% Yield Comunidad',
    INCOME_MODEL_AUTODISTRIB: 'Reparto Automático On-Chain Real Yield',
    SECTION_TARGET_DISTRIB: '📌 Distribución Target de Activos de Reserva',
    TH_REAL_USD_VAL: 'Valor USD Real',
    TH_TREASURY_ROLE: 'Función en Tesorería',
    ROLE_MORPHO_P2P: 'Morpho Yield + Créditos P2P + Líquido',
    ROLE_DEX_BUYS: 'Compras DEX en Mercado Secundario',
    ROLE_AUTO_STAKE: 'Auto-stake Institucional Governance',
    SECTION_GLOBAL_CONFIG: '⚙️ Configuración Global de Parámetros y Comisiones',
    LABEL_DEPOSIT_FEE_PCT: 'COMISIÓN DE DEPÓSITO TESORERÍA (%)',
    LABEL_REDEEM_FEE_PCT: 'COMISIÓN DE CANJE DIRECTO / REDEEM (%)',
    LABEL_P2P_FEE_PCT: 'FEE ORIGINACIÓN PRÉSTAMOS P2P (%)',
    BTN_PROPOSE_DAO: '🏛️ Proponer Votación DAO (72h)',
    BTN_SAVE_SANDBOX: '🧪 Guardar (Sandbox)',
    SECTION_VAULT_ADDRESSES: '💼 Direccionamiento de Bóvedas Pure DeFi',
    LABEL_BUNKER_WALLET: '🏛️ BILLETERA BUNKER TESORERÍA (CONTRATO SUB-RESERVA)',
    LABEL_COMMUNITY_YIELD_VAULT: '💎 BÓVEDA COMMUNITY REAL YIELD (BÓVEDA REAL YIELD STAKERS)',
    SECTION_PROMOS_TITLE: '🎁 Gestor de Promociones, Incentivos & Eventos Especiales',
    LABEL_LAUNCH_PROMO: '✨ Lanzar Nueva Campaña Promocional On-Chain',
    BTN_PROPOSE_PROMO: '🏛️ Proponer Presupuesto Promocional en Governor (72h)',
    BTN_ACTIVATE_PROMO: '🚀 Crear y Activar Campaña Promocional On-Chain',
    SECTION_SECURITY_TITLE: '🛡️ Consola de Seguridad de Emergencia & Circuit Breaker',
    SUBTITLE_RESET_BREAKER: '⚡ Descongelar Circuit Breaker',
    DESC_RESET_BREAKER: 'Restablece la operatividad del contrato tras una parada de seguridad provocada por alta volatilidad o congelamiento de oráculo.',
    BTN_PROPOSE_RESET_BREAKER: '🛡️ Proponer Reset Breaker / Security Council Multisig (72h)',
    BTN_RESET_BREAKER_DEV: '🔓 Reiniciar Circuit Breaker (Devnet)',
    DESC_ORACLE_PROD: 'En Mainnet Live, los precios son provistos automáticamente por los agregadores de nodos descentralizados de Chainlink.',
    DESC_ORACLE_DEV: 'Actualiza el valor del feed de prueba de USDC en la sandbox para simular fluctuaciones de mercado.',
    BTN_PROPOSE_FEED: '🏛️ Proponer Feed en Governor (72h)',
    BTN_UPDATE_FEED: 'Actualizar'
  },

  ADMIN: {
    TITLE_SANDBOX: '🧪 ENTORNO DE PRUEBAS SANDBOX (Anvil Devnet — Chain ID 31337)',
    TITLE_PROD: '🏛️ PRODUCCIÓN PURE DEFI MAINNET-READY — 0 EOA Admin Keys',
    SUBTITLE_SANDBOX: 'Herramientas de simulación, auditoría de oráculos y control de estabilidad para desarrolladores.',
    SUBTITLE_PROD: 'Protocolo descentralizado gobernado exclusivamente mediante Timelock DAO.',
    CARD_ORACLE_TITLE: '🔮 Ajuste de Feed de Oráculo Chainlink',
    LABEL_ORACLE_PRICE: 'Precio Oráculo USDC (USD):',
    BTN_UPDATE_ORACLE: '🔮 Actualizar Feed del Oráculo',
    CARD_WEIGHTS_TITLE: '⚖️ Rebalanceo de Pesos Objetivo de Tesorería',
    LABEL_STABLES_WEIGHT: 'USDC Morpho (%):',
    LABEL_WBTC_WEIGHT: 'WBTC Lombard (%):',
    LABEL_WETH_WEIGHT: 'WETH Lido (%):',
    LABEL_ALTS_WEIGHT: 'Préstamos & ALPHA (%):',
    BTN_ADJUST_WEIGHTS: '⚖️ Rebalancear Pesos On-Chain',
    CARD_BREAKER_TITLE: '⚡ CircuitBreaker & Resiliencia ante Volatilidad',
    BREAKER_STATUS_ACTIVE: '🟢 CircuitBreaker Estado: ACTIVO & OPERATIVO',
    BREAKER_STATUS_FROZEN: '🔴 CircuitBreaker Estado: ACTIVADO (CONGELADO)',
    BTN_CHECK_DEVIATION: '🔍 Evaluar Desviación de Volatilidad',
    BTN_RESET_BREAKER: '⚡ Reiniciar CircuitBreaker',
    CARD_RESET_TITLE: '🔄 Restaurar Snapshot Blockchain (Sandbox EVM Reset)',
    BTN_RESET_EVM: '🔄 Revertir Snapshot Blockchain',
    CARD_CAMPAIGN_TITLE: '🎁 Crear Campaña Promocional (PromotionalIncentiveVault)',
    LABEL_CAMPAIGN_NAME: 'Nombre de Campaña:',
    LABEL_CAMPAIGN_AMOUNT: 'Fondo ALPHA Asignado:',
    BTN_CREATE_CAMPAIGN: '🎁 Activar Campaña Promocional',
    LABEL_TOGGLE_VIEW: 'Simular Vista:',
    BTN_TOGGLE_SANDBOX: '🧪 Sandbox Devnet',
    BTN_TOGGLE_PROD: '🏛️ Pure DeFi Live',
    CARD_BUYBACK_TITLE: '🛡️ Peg Stabilizer & Buyback Engine (10 Candados)',
    LABEL_BUYBACK_SAFETY: 'Protocol Safety:',
    LABEL_BUYBACK_LOCKS_ACTIVE: '10/10 Candados Activos On-Chain',
    BUYBACK_LOCKS_LIST: [
      '• Umbral Descuento: ≥5.00% vs NAV',
      '• Presupuesto Diario: ≤2.50% de Reserva Líquida',
      '• Cooldown: 1 Hora Rate Limiting',
      '• Invariante PoR: Respaldo ≥102.00%'
    ],
    INPUT_BUYBACK_PLACEHOLDER: 'USDC a Invertir',
    BTN_BUYBACK_EXECUTING: 'Ejecutando...',
    BTN_BUYBACK_SUBMIT: '🔥 Recomprar & Quemar',
    WARNING_PURE_DEFI_TITLE: '🛑 Escrituras Directas Desactivadas (Pure DeFi Enforcement)',
    WARNING_PURE_DEFI_BODY: 'Cualquier intento de ejecutar un writeContract directo a OracleHub o TreasuryManager desde una billetera privada revertirá con "AccessControl: account is missing role". Todos los cambios deben presentarse como propuestas de gobernanza en el formulario inferior.',
    LABEL_ACTION_FUNCTION: '2. Acción a Ejecutar (Function):',
    LABEL_PARAM_1: 'Parámetro 1 (Dirección / Valor):',
    LABEL_PARAM_2: 'Parámetro 2 (Feed Secondary / Staleness):',
    LABEL_BREAKER_STATE: 'Estado del Interruptor:'
  },

  ANALYTICS_CHARTS: {
    TITLE: '📈 Analíticas del Protocolo & Crecimiento Histórico',
    TAB_RESERVES: 'Total Reservas (USD)',
    TAB_NAV: 'Evolución NAV / Share',
    TAB_BORROW: 'Volumen Préstamos P2P',
    TAB_BURN: 'Quema Deflacionaria ALPHA',
    RANGE_7D: '7D',
    RANGE_30D: '30D',
    RANGE_90D: '90D',
    RANGE_1Y: '1Y',
    RANGE_ALL: 'TODO',
    MAIN_TITLE: 'Analíticas On-Chain & Reservas Exógenas',
    SUBTITLE_PREFIX: 'Métricas leídas en vivo',
    SUBTITLE_SUFFIX: 'ALPHA Staked en Gobernanza',
    BADGE_POR_ACTIVE: '🛡️ PoR Activo:',
    TAB_CARD_RESERVES: '💎 RESERVAS EXÓGENAS',
    TAB_CARD_CASHFLOW: '💸 FLUJO DE CAJA BRUTO REAL',
    TAB_CARD_APY: '⚡ APY PONDERADO CONTRACTUAL',
    LABEL_LIABILITIES_PREFIX: 'Pasivo:',
    LABEL_POR_PREFIX: 'PoR:',
    LABEL_CASHFLOW_SUBTEXT: 'Bonos + Préstamos P2P',
    LABEL_YIELD_PREFIX: 'Yield:',
    LABEL_ON_CHAIN_YIELD: 'Rendimiento On-Chain',
    LABEL_FLYWHEEL_BOOST: '+ Flywheel Boost',
    TOOLTIP_DATE_PREFIX: '📅',
    TOOLTIP_TOTAL_RESERVES: 'Total Reservas:',
    TOOLTIP_STABLES: 'Stablecoins (USDC):',
    TOOLTIP_BTC: 'Bitcoin (WBTC):',
    TOOLTIP_ETH: 'Ethereum (WETH):',
    TOOLTIP_CASHFLOW: 'Flujo de Caja Real:',
    TOOLTIP_APY: 'APY PONDERADO REAL:',
    LEGEND_STABLES: '🟢 Stablecoins (Morpho + P2P - ',
    LEGEND_BTC: '🟠 Bitcoin (Lombard - ',
    LEGEND_ETH: '🔵 Ethereum (Lido - ',
    LEGEND_CASHFLOW: 'Flujo de Caja Bruto',
    LEGEND_APY: 'APY Ponderado On-Chain'
  },

  MODALS: {
    TRANSACTION_CONFIRM: {
      TITLE_DEFAULT: 'Confirmar Transacción On-Chain',
      FLOW_IN_LABEL: 'ENVIAS / ENTRADA',
      FLOW_OUT_LABEL: 'RECIBES / ESTIMADO',
      SUMMARY_SECTION_TITLE: 'Resumen Operativo & Parámetros',
      TARGET_CONTRACT_LABEL: 'Contrato Objetivo:',
      BTN_CANCEL: 'Cancelar',
      BTN_CONFIRM_DEFAULT: '✍️ Confirmar y Firmar',
      BTN_SIGNING: '⏳ Firmando...'
    },
    APY_BREAKDOWN: {
      TITLE: 'Desglose de Reservas y Rendimiento Anualizado en Tiempo Real',
      SUBTITLE_PREFIX: 'Reservas Totales:',
      SUBTITLE_STAKING_PREFIX: 'Staking:',
      HIGHLIGHT_LABEL: 'RENDIMIENTO ANUALIZADO TOTAL EN TIEMPO REAL',
      HIGHLIGHT_USD_SUFFIX: 'USD / año generados por las Reservas',
      HIGHLIGHT_BASE_LABEL: '🏦 Base Reservas:',
      HIGHLIGHT_FLYWHEEL_LABEL: '💸 Flywheel Recompensas:',
      SECTION_1_TITLE: '1. DÓNDE ESTÁN LAS RESERVAS & RENDIMIENTO ANUALIZADO (ON-CHAIN)',
      SECTION_1_BASE_RATE: 'Tasa Base:',
      MORPHO_TITLE: '🏦 Morpho Blue MetaMorpho Vault',
      MORPHO_LOCATION_PREFIX: 'Ubicación:',
      MORPHO_OF_RESERVES: 'de Reservas',
      MORPHO_VAULT_RATE: 'Tasa Vault On-Chain:',
      MORPHO_TOTAL_ADD: 'APR al Total',
      BUFFER_TITLE: '💧 Búfer Líquido de Tesorería',
      BUFFER_DESC: 'Liquidez Inmediata para Rescates',
      LBTC_TITLE: '₿ Lombard LBTC Bitcoin Liquid Staking',
      LBTC_DESC: 'Rendimiento Variable',
      WSTETH_TITLE: 'Ξ Lido wstETH Ethereum Liquid Staking',
      TREASURY_LOANS_TITLE: '🏛️ Fondo de Préstamos Directos Tesorería (Línea de Crédito Máx. de Reservas)',
      TREASURY_LOANS_MAX: 'Fondo Total Máximo:',
      TREASURY_LOANS_LENT: 'Prestado:',
      ALPHA_STAKING_TITLE: '🥩 Staking de Tokens ALPHA & Gobernanza DAO',
      ALPHA_STAKING_ACTIVE: 'Posición Activa:',
      ALPHA_STAKING_BACKING: 'Respaldo Directo NAV:',
      SECTION_2_TITLE: '2. COMISIONES DE PROTOCOLO FLUIDAS (FLYWHEEL REAL YIELD)',
      SECTION_2_BOOST: 'Boost Staking:',
      BOND_FEES_TITLE: '🏷️ Comisiones por Emisión de Bonos Vestados (Mint Fee On-Chain)',
      BOND_FEES_DESC: 'Recaudación Anualizada de Comisiones:',
      P2P_FEES_TITLE: '🤝 Comisiones de Originación P2P (Origination Fee On-Chain)',
      P2P_FEES_DESC: 'Recaudación Anualizada sobre Préstamos:',
      MARGIN_FEES_TITLE: '💰 Spread de Margen de Interés (Interest Spread On-Chain)',
      MARGIN_FEES_DESC: 'Comisión del protocolo sobre los intereses generados on-chain',
      MATH_FORMULA_TITLE: '🔍 Fórmula Matématica Exacta On-Chain:',
      MATH_FORMULA_CODE: 'Rendimiento_Anual_USD = Σ (Ubicación_USD_i × Tasa_i) + Comisiones_Protocolo_USDC',
      BTN_UNDERSTOOD: '✅ Entendido y Verificado'
    },
    REFERRAL: {
      TITLE: '🤝 Programa de Referidos Institucional',
      SUBTITLE: 'Comparte tu enlace de referido y obtén bonificaciones de comisiones on-chain.',
      LINK_LABEL: 'Tu Enlace de Referido Exclusivo:',
      BTN_COPY: '📋 Copiar Enlace',
      BTN_COPIED: '✅ Enlace Copiado',
      TIER_DESC: 'Recibe hasta un 0.50% de cashback en comisiones por cada bono adquirido con tu dirección.',
      SHARE_TEXT: '🚀 Unete a Alpha Centauri y obtén hasta un 25% de descuento en Bonos Vestados respaldados por Proof of Reserves. ¡Invierte con auto-custodia on-chain!',
      BENEFITS_TITLE: 'Beneficios Exclusivos del Programa:',
      BENEFIT_1_TEXT: 'Comisión Directa en USDC transferidos a tu wallet por cada amigo que compre un Bono.',
      BENEFIT_2_TEXT: 'Descuento Progresivo para tus invitados en la compra de sus Bonos Vestados.',
      BENEFIT_3_TEXT: 'Sin Límites de Ingresos: Gana comisiones recurrentes por cada referido activo.',
      SOCIAL_SHARE_TITLE: 'COMPARTIR DIRECTAMENTE EN REDES SOCIALES:',
      BTN_TWITTER: '🐦 X / Twitter',
      BTN_TELEGRAM: '💬 Telegram',
      BTN_WHATSAPP: '📱 WhatsApp',
      BTN_LINKEDIN: '💼 LinkedIn'
    },
    ACTIVITY_LOG: {
      TITLE: '📜 Registro de Actividad On-Chain en Tiempo Real',
      EMPTY: 'No hay transacciones registradas en esta sesión.'
    }
  },

  TOASTS_AND_LOGS: {
    FAUCET_INFO: 'Reclamando 10,000 USDC mock del Faucet...',
    FAUCET_SUCCESS: '¡10,000 USDC mock recibidos en tu billetera!',
    DEPOSIT_START: 'Depositando USDC en Tesorería...',
    DEPOSIT_APPROVING: 'Aprobando USDC para Tesorería...',
    DEPOSIT_SUCCESS: 'Depósito completado. Shares ALPHA acuñadas a valor NAV.',
    REDEEM_START: 'Rescatando ALPHA shares en Tesorería...',
    REDEEM_SUCCESS: 'Rescate completado. USDC transferidos a tu billetera.',
    POR_AUDIT_SUCCESS: 'Proof of Reserves auditado con éxito on-chain.',
    STAKE_START: 'Iniciando staking de tokens ALPHA...',
    STAKE_SUCCESS: '¡Staking completado exitosamente on-chain!',
    UNSTAKE_START: 'Retirando tokens ALPHA del contrato de Staking...',
    UNSTAKE_SUCCESS: '¡Unstake completado! ALPHA liberado a tu billetera.',
    CLAIM_YIELD_START: 'Reclamando Real Yield vía RealYieldRouter...',
    CLAIM_YIELD_SUCCESS: '¡Real Yield reclamado con éxito!',
    BOND_BUY_START: 'Adquiriendo Bono Vestado...',
    BOND_BUY_SUCCESS: '¡Bono Vestado adquirido! NFT de Posición acuñado.',
    BOND_CLAIM_START: 'Reclamando bono vencido...',
    BOND_CLAIM_SUCCESS: '¡Bono vencido reclamado con éxito!',
    RAGEQUIT_START: 'Ejecutando Ragequit anticipado (15% penalización)...',
    RAGEQUIT_SUCCESS: 'Ragequit ejecutado. Reembolso recibido en la billetera.',
    P2P_OFFER_START: 'Creando oferta de préstamo P2P...',
    P2P_OFFER_SUCCESS: '¡Oferta P2P creada! NFT custodiado en escrow.',
    P2P_FUND_START: 'Financiando préstamo P2P...',
    P2P_FUND_SUCCESS: '¡Préstamo financiado con éxito!',
    P2P_CANCEL_START: 'Cancelando oferta P2P...',
    P2P_CANCEL_SUCCESS: '¡Oferta cancelada! NFT devuelto a tu billetera.',
    P2P_REPAY_START: 'Reembolsando préstamo P2P...',
    P2P_REPAY_SUCCESS: '¡Préstamo reembolsado! Garantía liberada.',
    P2P_LIQUIDATE_START: 'Ejecutando auto-liquidación de préstamo...',
    P2P_LIQUIDATE_SUCCESS: '¡Liquidación ejecutada! Colateral transferido al prestamista.',
    TREASURY_BORROW_START: 'Solicitando crédito directo a la Tesorería...',
    TREASURY_BORROW_SUCCESS: '¡Préstamo desembolsado por la Tesorería!',
    ORACLE_UPDATE_SUCCESS: '¡Precio de oráculo actualizado con éxito!',
    WEIGHTS_ADJUST_SUCCESS: '¡Pesos de tesorería rebalanceados con éxito on-chain!',
    BREAKER_RESET_SUCCESS: '¡CircuitBreaker reiniciado con éxito!',
    BLOCKCHAIN_RESET_SUCCESS: '¡Entorno EVM restaurado desde snapshot!'
  }
} as const;
